package javaapplication4;


import java.awt.Component;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Query.java
 *
 * Created on Jun 11, 2012, 7:36:57 AM
 */

/**
 *
 * @author Moinul Joje
 */
public class Query extends javax.swing.JFrame {
    private Component jframe;

    /** Creates new form Query */
    public Query() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        proceedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Info about Normal User");

        jLabel2.setText("Name");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(26, 26, 26)))
                .addComponent(proceedButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedButton)
                    .addComponent(saveButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == saveButton) {

            /// Confirm addition of information to database
            int choice = JOptionPane.showConfirmDialog(jframe,"Add this information to the database?","Normal User",JOptionPane.YES_NO_OPTION);

            // If YES
            if(choice == JOptionPane.YES_OPTION) {

                try {

                    // load database driver class
                    Class.forName( "sun.jdbc.odbc.JdbcOdbcDriver");

                    // connect to database
                    java.sql.Connection connection = DriverManager.getConnection("jdbc:odbc:Personnel" );

                    // create Statement to query database
                    java.sql.Statement statement = connection.createStatement();

                    // Add new acount to Master table
                    java.sql.Statement stmt = connection.createStatement();
                    stmt.executeUpdate(
                            "INSERT INTO Normal User(user_name)VALUES "+"('"

                            +nameText.getText()
                            +"')");

                    JOptionPane.showMessageDialog(null,"Data Entered into Database Successfully");
                            nameText.setText("");
                            



                    statement.close(); // Close statement
                    connection.close(); // Close connection

                    setVisible(false); // Hide frame

                }  // end try

                // detect problems interacting with the database
                catch ( java.sql.SQLException sqlException ) {
                    JOptionPane.showMessageDialog( null,
                            sqlException.getMessage(), "Database Error",
                            JOptionPane.ERROR_MESSAGE );

                    System.exit( 1 );
                }


                catch ( ClassNotFoundException classNotFound ) {
                    JOptionPane.showMessageDialog( null,
                            classNotFound.getMessage(), "Driver Not Found",
                            JOptionPane.ERROR_MESSAGE );

                    System.exit( 1 );
                }



            }
            // If NO
            else{
                            nameText.setText("");


                setVisible(false); // Hide Frame

            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==proceedButton){
       MainScreen ms=new MainScreen();
       ms.setVisible(true);
        }
        setVisible(false);
    }//GEN-LAST:event_proceedButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Query().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton proceedButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
