

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewEntry.java
 *
 * Created on Jun 11, 2012, 4:17:27 AM
 */

/**
 *
 * @author Moinul Joje
 */
import java.awt.Component;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.JFrame;
public class NewEntry extends javax.swing.JFrame {
    private Component jframe;

    /** Creates new form NewEntry */
    public NewEntry() {
        setTitle("New Info Inserter");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstnameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastnameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        middlenameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nicknameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maritalstatusText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        res_phone_noText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        off_phone_noText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cell_numberText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        email_addressText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        company_nameText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        dptnameText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setText("Inserter of New Information");

        jLabel2.setText("First Name");

        firstnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        lastnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Middle Name");

        middlenameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Nick Name");

        nicknameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameTextActionPerformed(evt);
            }
        });

        jLabel6.setText("Gender");

        genderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Marital Status");

        maritalstatusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritalstatusTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Age");

        ageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Address");

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Residential Phone NO");

        res_phone_noText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_phone_noTextActionPerformed(evt);
            }
        });

        jLabel11.setText("Office Phone NO");

        off_phone_noText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off_phone_noTextActionPerformed(evt);
            }
        });

        jLabel12.setText("Cell Phone NO");

        cell_numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell_numberTextActionPerformed(evt);
            }
        });

        jLabel13.setText("E Mail Address");

        email_addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_addressTextActionPerformed(evt);
            }
        });

        jLabel14.setText("Company Name");

        company_nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_nameTextActionPerformed(evt);
            }
        });

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Dept. Name");

        dptnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptnameTextActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(company_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(ageText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(middlenameText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(firstnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(cell_numberText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(res_phone_noText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_addressText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(off_phone_noText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(addressText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(dptnameText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(maritalstatusText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(nicknameText, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(lastnameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addGap(30, 30, 30)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lastnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(middlenameText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maritalstatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(res_phone_noText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(off_phone_noText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell_numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(email_addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(company_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(dptnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        // TODO add your handling code here:
        if (evt.getSource() == submitButton) {

            /// Confirm addition of information to database
            int choice = JOptionPane.showConfirmDialog(jframe,"Add this information to the database?","Persons",JOptionPane.YES_NO_OPTION);

            // If YES
            if(choice == JOptionPane.YES_OPTION) {

                try {

                    // load database driver class
                    Class.forName( "sun.jdbc.odbc.JdbcOdbcDriver");

                    // connect to database
                    java.sql.Connection connection = DriverManager.getConnection("jdbc:odbc:personnel" );

                    // create Statement to query database
                    java.sql.Statement statement = connection.createStatement();

                    // Add new acount to Master table
                    java.sql.Statement stmt = connection.createStatement();
                    stmt.executeUpdate(
                            "INSERT INTO persons(first_name,last_name,middle_name,nickname,gender,maritalstatus,age,address,res_phone_no,off_phone_no,cell_number,email_address,company_name,dept_name)VALUES "+"('"

                            +"','"+firstnameText.getText()
                            +"','"+lastnameText.getText()
                            +"','"+middlenameText.getText()
                            +"','"+nicknameText.getText()
                            +"','"+genderText.getText()
                            +"','"+maritalstatusText.getText()
                            +"','"+ageText.getText()
                            +"','"+addressText.getText()
                            +"','"+res_phone_noText.getText()
                            +"','"+off_phone_noText.getText()
                            +"','"+cell_numberText.getText()
                            +"','"+email_addressText.getText()
                            +"','"+company_nameText.getText()
                            +"','"+dptnameText.getText()
                            +"')");

                    JOptionPane.showMessageDialog(null,"Data Entered into Database Successfully");
                            firstnameText.setText("");
                            lastnameText.setText("");
                            middlenameText.setText("");
                            nicknameText.setText("");
                            genderText.setText("");
                            maritalstatusText.setText("");
                            ageText.setText("");
                            addressText.setText("");
                            res_phone_noText.setText("");
                            off_phone_noText.setText("");
                            cell_numberText.setText("");
                            email_addressText.setText("");
                            company_nameText.setText("");
                            dptnameText.setText("");
      


                    statement.close(); // Close statement
                    connection.close(); // Close connection

                    setVisible(false); // Hide frame

                }  // end try

                // detect problems interacting with the database
                catch ( java.sql.SQLException sqlException ) {
                    JOptionPane.showMessageDialog( null,
                            sqlException.getMessage(), "Database Error",
                            JOptionPane.ERROR_MESSAGE );

                    System.exit( 1 );
                }


                catch ( ClassNotFoundException classNotFound ) {
                    JOptionPane.showMessageDialog( null,
                            classNotFound.getMessage(), "Driver Not Found",
                            JOptionPane.ERROR_MESSAGE );

                    System.exit( 1 );
                }



            }
            // If NO
            else{
                            firstnameText.setText("");
                            lastnameText.setText("");
                            middlenameText.setText("");
                            nicknameText.setText("");
                            genderText.setText("");
                            maritalstatusText.setText("");
                            ageText.setText("");
                            addressText.setText("");
                            res_phone_noText.setText("");
                            off_phone_noText.setText("");
                            cell_numberText.setText("");
                            email_addressText.setText("");
                            company_nameText.setText("");
                            dptnameText.setText("");

                            
                setVisible(false); // Hide Frame

            }
        }
}//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==clearButton){
                            firstnameText.setText("");
                            lastnameText.setText("");
                            middlenameText.setText("");
                            nicknameText.setText("");
                            genderText.setText("");
                            maritalstatusText.setText("");
                            ageText.setText("");
                            addressText.setText("");
                            res_phone_noText.setText("");
                            off_phone_noText.setText("");
                            cell_numberText.setText("");
                            email_addressText.setText("");
                            company_nameText.setText("");
                            dptnameText.setText("");

                            
        }
}//GEN-LAST:event_clearButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==cancelButton){
          System.exit(0);
        }
}//GEN-LAST:event_cancelButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==backButton){
       Options opt=new Options();
       opt.setVisible(true);
        }
        setVisible(false);
}//GEN-LAST:event_backButtonActionPerformed

    private void ageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextActionPerformed
        // TODO add your handling code here:
        try{
           int age=Integer.parseInt(this.ageText.getText());
        }catch(Exception E){
            JOptionPane.showMessageDialog(this,"Age should be numeric.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_ageTextActionPerformed

    private void res_phone_noTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_phone_noTextActionPerformed
        // TODO add your handling code here:
        try{
            int rph=Integer.parseInt(this.res_phone_noText.getText());
        }catch(Exception E){
            JOptionPane.showMessageDialog(this,"Phone number should be numeric.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_res_phone_noTextActionPerformed

    private void off_phone_noTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off_phone_noTextActionPerformed
        // TODO add your handling code here:
        try{
            int oph=Integer.parseInt(this.off_phone_noText.getText());
        }catch(Exception E){
            JOptionPane.showMessageDialog(this,"Phone number should be numeric.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_off_phone_noTextActionPerformed

    private void cell_numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell_numberTextActionPerformed
        // TODO add your handling code here:
        try{
           int cn=Integer.parseInt(this.cell_numberText.getText());
        }catch(Exception E){
            JOptionPane.showMessageDialog(this,"Phone number should be numeric.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_cell_numberTextActionPerformed

    private void firstnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_firstnameTextActionPerformed

    private void lastnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lastnameTextActionPerformed

    private void middlenameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_middlenameTextActionPerformed

    private void nicknameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nicknameTextActionPerformed

    private void genderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_genderTextActionPerformed

    private void maritalstatusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritalstatusTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_maritalstatusTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_addressTextActionPerformed

    private void email_addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_addressTextActionPerformed
        // TODO add your handling code here:
        try{
           String ea=email_addressText.getText();
        }catch(Exception E){
            JOptionPane.showMessageDialog(this,"String Required.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_email_addressTextActionPerformed

    private void company_nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_nameTextActionPerformed


    }//GEN-LAST:event_company_nameTextActionPerformed

    private void dptnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptnameTextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField ageText;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cell_numberText;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField company_nameText;
    private javax.swing.JTextField dptnameText;
    private javax.swing.JTextField email_addressText;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JTextField maritalstatusText;
    private javax.swing.JTextField middlenameText;
    private javax.swing.JTextField nicknameText;
    private javax.swing.JTextField off_phone_noText;
    private javax.swing.JTextField res_phone_noText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

}
